"""Add platform column to Game

Revision ID: 6a5a4d374359
Revises: 2e6c39315beb
Create Date: 2025-08-08 22:14:11.751133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5a4d374359'
down_revision = '2e6c39315beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours_played', sa.Float(), nullable=True))

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_name'))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('hours_played')
        batch_op.drop_column('rating')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
